flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R: R/first.R
  tests: tests/testthat/test-first.R
  vignettes: vignettes/get_one.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: get_one
    open_vignette: true
    check: true
    document: true
    overwrite: ask
