# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand

test_that("get_one_file_size works for an existing file", {
  # Créer un fichier temporaire
  temp_file <- tempfile(fileext = ".txt")
  writeLines("Test content", temp_file)
  
  result <- get_one_file_size(temp_file)
  
  expect_equal(result$name, temp_file)
  expect_equal(result$size, file.size(temp_file))
  expect_equal(result$extension, "txt")
})

test_that("get_one_file_size throws an error for a non-existing file", {
  non_existing_file <- tempfile(fileext = ".txt")
  unlink(non_existing_file)  # S'assurer que le fichier n'existe pas
  
  expect_error(get_one_file_size(non_existing_file), "Le fichier n'existe pas")
})

test_that("get_one_file_size handles empty files correctly", {
  # Créer un fichier temporaire vide
  empty_file <- tempfile(fileext = ".md")
  file.create(empty_file)
  
  result <- get_one_file_size(empty_file)
  
  expect_equal(result$name, empty_file)
  expect_equal(result$size, 0)
  expect_equal(result$extension, "md")
})

test_that("get_one_file_size handles files with no extension correctly", {
  # Créer un fichier temporaire sans extension
  no_ext_file <- tempfile()
  writeLines("No extension content", no_ext_file)
  
  result <- get_one_file_size(no_ext_file)
  
  expect_equal(result$name, no_ext_file)
  expect_equal(result$size, file.size(no_ext_file))
  expect_equal(result$extension, "")
})
