# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand

#' get_one_file_size 
#'
#' @param file a file
#' @importFrom tools file_ext
#' @return a dataframe with filename, size and extension
#' 
#' @export
#'
#' @examples
#' temp_file_1 <- tempfile()
#' writeLines("Test content", temp_file_1)
#' get_one_file_size(temp_file_1)
get_one_file_size <- function(file) {
  if (file.exists(file)) {
    size <- file.size(file)
    extension <- tools::file_ext(file)
  } else {
    stop("Le fichier n'existe pas")
  }
  result <- data.frame(name = file, size = size, extension=extension, stringsAsFactors = FALSE)
  return(result)
}
