# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand

#' get_all_file_size
#' 
#' Elle prend un chemin de dossier en paramètre, et map la fonction get_one_file_size pour n’obtenir qu’un seul tableau.
#' 
#' @param path un chemin
#' @importFrom purrr map
#' @importFrom dplyr bind_rows
#' @return un tableau
#' 
#' @export
#' 
#' 
#' @examples
#' get_all_file_size(path = ".")
get_all_file_size <- function(path) {
  files <- list.files(path, full.names = TRUE)
  result <- purrr::map(files, get_one_file_size) |> dplyr::bind_rows()
  return(result)
}

